name: Build

on:
  pull_request:
  push:
    branches:
      - main
    
env:
  CARGO_PKG_VERSION: "0.2.${{ github.run_number }}"
  
permissions:
  contents: write

jobs:
  build-linux-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Rust version
        id: rust-version
        run: echo "version=$(rustc --version | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.rustup
            target
          key: ${{ runner.os }}-rust-${{ steps.rust-version.outputs.version }}
      - name: Build Linux binary and plugin
        run: |
          cargo install cargo-edit
          cargo set-version --workspace "$CARGO_PKG_VERSION"
          mkdir -p output
          cargo build --release
          cp target/release/rbx-studio-mcp output/rbx-studio-mcp-linux-x86_64
          chmod +x output/rbx-studio-mcp-linux-x86_64
          ./target/release/rbx-studio-mcp --write-plugin output/MCPStudioPlugin.rbxm
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux-rbx-studio-mcp-and-plugin
          path: |
            output/rbx-studio-mcp-linux-x86_64
            output/MCPStudioPlugin.rbxm

  release:
    runs-on: ubuntu-latest
    if:  ${{ github.ref_name == github.event.repository.default_branch }}
    needs: [build-linux-plugin]
    steps:
      - run: mkdir -p output
      - uses: actions/download-artifact@v4
        with:
          path: output
          merge-multiple: true
      - name: Create release
        uses: Roblox-ActionsCache/softprops-action-gh-release@v1
        with:
          tag_name: v${{ env.CARGO_PKG_VERSION }}
          release_name: Release v${{ env.CARGO_PKG_VERSION }}
          files: output/*
